default: &default
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

production:
  <<: *default

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV["DB_NAME"] || 'heroku_connect_ex' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV["DB_NAME_TEST"] || 'heroku_connect_ex_test' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
